spring:
  application:
    # Servisin Eureka'da ve Gateway'de görünecek adı
    name: course-service
  main:
    web-application-type: servlet
  config:
    import: "configserver:http://localhost:8888" # Yeni Spring Cloud sürümü için
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  # Redis Cache Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

