spring:
  application:
    name: course-service  # Config Server bu isme göre course-service.yml dosyasını arar

  config:
    # Config Server'a bağlanma ayarı
    import: "optional:configserver:http://localhost:8888/"

# Eğer Config Server kapalıysa veya hata verirse uygulamanın çökmemesi için (Opsiyonel)
cloud:
  config:
    fail-fast: false